#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop the YugabyteDB binary
  vars:
    bin_name: "{{ yugabyte_bin_name }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: stop
