#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch Yugabyte DB Kubernetes logs
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: k8s/fetch_logs
  when: yugabyte_use_k8s or yugabyte_use_openshift

- name: Fetch the Yugabyte DB container logs
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: container/fetch_logs
  when: yugabyte_use_container

- name: Fetch the Yugabyte DB binary logs
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: bin/fetch_logs
  when: yugabyte_use_bin
