#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# =========================
# Configuration
# =========================
- name: Ensure the config directory for fxconfig exists
  ansible.builtin.file:
    path: "{{ fxconfig_remote_config_dir }}"
    state: directory
    mode: "0o755"

- name: Set fxconfig effective orderer address to OpenShift Route
  vars:
    fxconfig_orderer_openshift_route_port: "{{ 443 if hostvars[orderer_router_host].orderer_use_tls is defined and hostvars[orderer_router_host].orderer_use_tls else 80 }}"
  ansible.builtin.set_fact:
    fxconfig_orderer_address: "{{ hostvars[orderer_router_host].orderer_openshift_route }}:{{ fxconfig_orderer_openshift_route_port }}"
  when:
    - hostvars[orderer_router_host].orderer_use_openshift is defined
    - hostvars[orderer_router_host].orderer_use_openshift
    - hostvars[orderer_router_host].orderer_openshift_route is defined

- name: Set fxconfig effective committer sidecar address to OpenShift Route
  vars:
    fxconfig_committer_sidecar_openshift_route_port: "{{ 443 if hostvars[committer_sidecar_host].committer_use_tls is defined and hostvars[committer_sidecar_host].committer_use_tls else 80 }}"
  ansible.builtin.set_fact:
    fxconfig_committer_sidecar_address: "{{ hostvars[committer_sidecar_host].committer_openshift_route }}:{{ fxconfig_committer_sidecar_openshift_route_port }}"
  when:
    - hostvars[committer_sidecar_host].committer_use_openshift is defined
    - hostvars[committer_sidecar_host].committer_use_openshift
    - hostvars[committer_sidecar_host].committer_openshift_route is defined

- name: Set fxconfig effective committer query-service address to OpenShift Route
  vars:
    fxconfig_committer_query_service_openshift_route_port: "{{ 443 if hostvars[committer_query_service_host].committer_use_tls is defined and hostvars[committer_query_service_host].committer_use_tls else 80 }}"
  ansible.builtin.set_fact:
    fxconfig_committer_query_service_address: "{{ hostvars[committer_query_service_host].committer_openshift_route }}:{{ fxconfig_committer_query_service_openshift_route_port }}"
  when:
    - fxconfig_has_query_service
    - hostvars[committer_query_service_host].committer_use_openshift is defined
    - hostvars[committer_query_service_host].committer_use_openshift
    - hostvars[committer_query_service_host].committer_openshift_route is defined

- name: Set fxconfig effective orderer address to k8s NodePort
  ansible.builtin.set_fact:
    fxconfig_orderer_address: "{{ hostvars[orderer_router_host].actual_host }}:{{ hostvars[orderer_router_host].orderer_k8s_rpc_node_port }}"
  when:
    - hostvars[orderer_router_host].orderer_openshift_route is not defined
    - hostvars[orderer_router_host].orderer_k8s_rpc_node_port is defined

- name: Set fxconfig effective committer sidecar address to k8s NodePort
  ansible.builtin.set_fact:
    fxconfig_committer_sidecar_address: "{{ hostvars[committer_sidecar_host].actual_host }}:{{ hostvars[committer_sidecar_host].committer_k8s_rpc_node_port }}"
  when:
    - hostvars[committer_sidecar_host].committer_openshift_route is not defined
    - hostvars[committer_sidecar_host].committer_k8s_rpc_node_port is defined

- name: Set fxconfig effective committer query-service address to k8s NodePort
  ansible.builtin.set_fact:
    fxconfig_committer_query_service_address: "{{ hostvars[committer_query_service_host].actual_host }}:{{ hostvars[committer_query_service_host].committer_k8s_rpc_node_port }}"
  when:
    - fxconfig_has_query_service
    - hostvars[committer_query_service_host].committer_openshift_route is not defined
    - hostvars[committer_query_service_host].committer_k8s_rpc_node_port is defined

- name: Setup the fxconfig configuration file
  vars:
    fxconfig_config_dir: >-
      {{
        fxconfig_remote_config_dir
        if fxconfig_use_bin
        else fxconfig_container_config_dir
      }}
    fxconfig_default_orderer_address: "{{ hostvars[orderer_router_host].actual_host }}:{{ hostvars[orderer_router_host].orderer_rpc_port }}"
    fxconfig_effective_orderer_address: "{{ fxconfig_orderer_address | default(fxconfig_default_orderer_address) }}"
    fxconfig_default_committer_query_service_address: >-
      {{
        (hostvars[committer_query_service_host].actual_host ~ ':' ~ hostvars[committer_query_service_host].committer_rpc_port)
        if fxconfig_has_query_service else ''
      }}
    fxconfig_effective_committer_query_service_address: "{{ fxconfig_committer_query_service_address | default(fxconfig_default_committer_query_service_address) }}"
    fxconfig_default_committer_sidecar_address: "{{ hostvars[committer_sidecar_host].actual_host }}:{{ hostvars[committer_sidecar_host].committer_rpc_port }}"
    fxconfig_effective_committer_sidecar_address: "{{ fxconfig_committer_sidecar_address | default(fxconfig_default_committer_sidecar_address) }}"
  ansible.builtin.template:
    src: "config.yaml.j2"
    dest: "{{ fxconfig_remote_config_dir }}/{{ fxconfig_config_file }}"
    mode: "0o644"

# =========================
# MSP material
# =========================
- name: Transfer the MSP material
  ansible.builtin.copy:
    src: "{{ fxconfig_msp_config_path }}"
    dest: "{{ fxconfig_remote_config_dir }}"
    remote_src: true
    mode: "preserve"

# =========================
# TLS material
# =========================
- name: Setup TLS material for fxconfig
  ansible.builtin.include_role:
    name: hyperledger.fabricx.fxconfig
    tasks_from: config/tls/transfer
  when:
    - (hostvars[committer_query_service_host].committer_use_tls is defined and hostvars[committer_query_service_host].committer_use_tls)
      or
      (hostvars[orderer_router_host].orderer_use_tls is defined and hostvars[orderer_router_host].orderer_use_tls)

# =========================
# mTLS material
# =========================
- name: Setup mTLS material for fxconfig
  ansible.builtin.include_role:
    name: hyperledger.fabricx.fxconfig
    tasks_from: config/mtls/transfer
  when:
    - (hostvars[committer_query_service_host].committer_use_mtls is defined and hostvars[committer_query_service_host].committer_use_mtls)
      or
      (hostvars[orderer_router_host].orderer_use_mtls is defined and hostvars[orderer_router_host].orderer_use_mtls)
