#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Install and start Node Exporter as a host binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.node_exporter
    tasks_from: bin/install
  when: node_exporter_use_bin

- name: Start the Node Exporter service
  ansible.builtin.include_role:
    name: hyperledger.fabricx.node_exporter
    tasks_from: bin/start
  when: node_exporter_use_bin

- name: Start Node Exporter container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.node_exporter
    tasks_from: container/start
  when: node_exporter_use_container

- name: Start Node Exporter on Kubernetes
  ansible.builtin.include_role:
    name: hyperledger.fabricx.node_exporter
    tasks_from: k8s/start
  when: node_exporter_use_k8s

- name: Start Node Exporter on OpenShift
  ansible.builtin.include_role:
    name: hyperledger.fabricx.node_exporter
    tasks_from: openshift/start
  when: node_exporter_use_openshift
