#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure Prometheus data directory exists
  ansible.builtin.file:
    path: "{{ prometheus_remote_data_dir }}"
    state: directory
    mode: "0o755"

- name: Start Prometheus container
  vars:
    container_name: "{{ prometheus_container_name }}"
    container_image: "{{ prometheus_image }}"
    container_command: >-
      --web.listen-address={{ prometheus_bind_address }}:{{ prometheus_port }}
      --config.file={{ prometheus_container_config_dir }}/{{ prometheus_config_file }}
      --storage.tsdb.path={{ prometheus_container_data_dir }}
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      --web.enable-remote-write-receiver
      --web.enable-lifecycle
      --enable-feature=native-histograms
      {% if prometheus_use_tls %}
      --web.config.file={{ prometheus_container_config_dir }}/{{ prometheus_web_config_file }}
      {% endif %}
    container_ports:
      - "{{ prometheus_port }}:{{ prometheus_port }}"
    container_volumes:
      - "{{ prometheus_remote_config_dir }}:{{ prometheus_container_config_dir }}:z,ro"
      - "{{ prometheus_remote_data_dir }}:{{ prometheus_container_data_dir }}:z"
    container_healthcheck_test: >-
      promtool check
      healthy
      {% if prometheus_use_tls %}
      --http.config.file={{ prometheus_container_config_dir }}/{{ prometheus_http_config_file }}
      --url https://{{ ansible_host }}:{{ prometheus_port }}
      {% else %}
      --url http://localhost:{{ prometheus_port }}
      {% endif %}
    container_wait_until_running: true
    container_wait_port: "{{ prometheus_port }}"
    container_run_as_host_user: true
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: start
