#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure output directory for namespace transactions to endorse exists
  ansible.builtin.file:
    path: "{{ fxconfig_remote_config_dir }}/to_submit"
    state: directory
    mode: "0o755"

- name: Transfer namespace transaction
  ansible.builtin.copy:
    src: "{{ fxconfig_tx_to_submit_path }}"
    dest: "{{ fxconfig_remote_config_dir }}/to_submit/ns.json"
    mode: preserve

- name: Submit transaction with fxconfig binary
  vars:
    # The < /dev/null is due to the fact that the command auto-detects
    # an stdin input. To prevent it, we nullify the stdin input.
    bin_command: >-
      {{ fxconfig_bin_name }} tx
      submit
      {{ fxconfig_remote_config_dir }}/to_submit/ns.json
      --config={{ fxconfig_remote_config_dir }}/{{ fxconfig_config_file }}
      {{ '--wait' if fxconfig_tx_submit_wait | bool else '' }} < /dev/null
    bin_run_with_tmux: false
    bin_collect_logs: false
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: start
